Don't expand JULIA_DEPOT_PATH if it may not be defined. (#57)

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -33,53 +33,54 @@ fi
 # Julia does not track when a precompilation file was last used, so we simply
 # remove files in the `compiled` directory until we are below the limit.
 
-COMPILED_DIR="${JULIA_DEPOT_PATH}/compiled"
-
 # default limit: 1 GiB
 COMPILED_LIMIT="${BUILDKITE_PLUGIN_JULIA_COMPILED_SIZE_LIMIT:-1073741824}"
 
-if [[ "${BUILDKITE_PLUGIN_JULIA_ISOLATED_DEPOT:-true}" == "true" ]] && [[ -d "${COMPILED_DIR}" ]]; then
-    COMPILED_SIZE_HUMAN=$(du -h -s "${COMPILED_DIR}" | cut -f 1)
-    # `-k` gives consistently the number of kilobytes on both macOS and Linux,
-    # without it BSD `du` would give the number of multiples of 512 bytes.
-    COMPILED_SIZE=$(($(du -k -s "${COMPILED_DIR}" | cut -f 1) * 1024))
-    echo "The compilation cache size is: ${COMPILED_SIZE_HUMAN}"
+if [[ "${BUILDKITE_PLUGIN_JULIA_ISOLATED_DEPOT:-true}" == "true" ]]; then
+    COMPILED_DIR="${JULIA_DEPOT_PATH}/compiled"
+    if [[ -d "${COMPILED_DIR}" ]]; then
+        COMPILED_SIZE_HUMAN=$(du -h -s "${COMPILED_DIR}" | cut -f 1)
+        # `-k` gives consistently the number of kilobytes on macOS and Linux,
+        # without it BSD `du` would give the number of multiples of 512 bytes.
+        COMPILED_SIZE=$(($(du -k -s "${COMPILED_DIR}" | cut -f 1) * 1024))
+        echo "The compilation cache size is: ${COMPILED_SIZE_HUMAN}"
 
-    if [[ ${COMPILED_SIZE} -gt ${COMPILED_LIMIT} ]]; then
-        echo "This is greater than the limit (${COMPILED_SIZE} > ${COMPILED_LIMIT} bytes), so we will clear the compilation cache"
+        if [[ ${COMPILED_SIZE} -gt ${COMPILED_LIMIT} ]]; then
+            echo "This is greater than the limit (${COMPILED_SIZE} > ${COMPILED_LIMIT} bytes), so we will clear the compilation cache"
 
-        # Remove files until we are below the limit
-        # We do this in Julia to avoid platform portability issues.
-        julia --color=yes -e '
-            function main(compilecache, size_str, limit_str)
-                size = parse(Int, size_str)
-                limit = parse(Int, limit_str)
+            # Remove files until we are below the limit
+            # We do this in Julia to avoid platform portability issues.
+            julia --color=yes -e '
+                function main(compilecache, size_str, limit_str)
+                    size = parse(Int, size_str)
+                    limit = parse(Int, limit_str)
 
-                # Get all files with their modification times
-                worklist = []
-                for (root, dirs, files) in walkdir(compilecache)
-                    for file in files
-                        path = joinpath(root, file)
-                        push!(worklist, (; path, stat=stat(path)))
+                    # Get all files with their modification times
+                    worklist = []
+                    for (root, dirs, files) in walkdir(compilecache)
+                        for file in files
+                            path = joinpath(root, file)
+                            push!(worklist, (; path, stat=stat(path)))
+                        end
+                    end
+
+                    # Sort by modification time (oldest first)
+                    sort!(worklist; by=entry->entry.stat.mtime)
+
+                    # Remove files until we are under the limit
+                    for entry in worklist
+                        rm(entry.path)
+                        size -= entry.stat.size
+                        size <= limit && break
                     end
                 end
 
-                # Sort by modification time (oldest first)
-                sort!(worklist; by=entry->entry.stat.mtime)
+                main(ARGS...)
+            ' "${COMPILED_DIR}" "${COMPILED_SIZE}" "${COMPILED_LIMIT}" || true
 
-                # Remove files until we are under the limit
-                for entry in worklist
-                    rm(entry.path)
-                    size -= entry.stat.size
-                    size <= limit && break
-                end
-            end
-
-            main(ARGS...)
-        ' "${COMPILED_DIR}" "${COMPILED_SIZE}" "${COMPILED_LIMIT}" || true
-
-        # Cleanup empty directories
-        find "${COMPILED_DIR}" -type d -empty -delete
+            # Cleanup empty directories
+            find "${COMPILED_DIR}" -type d -empty -delete
+        fi
     fi
 fi
 
@@ -90,52 +91,53 @@ fi
 # (and logs directories may not even persist) that doesn't work well.
 # So instead we remove directories based on their creation time.
 
-ARTIFACTS_DIR="${JULIA_DEPOT_PATH}/artifacts"
-
 # default limit: 10 GiB
 ARTIFACTS_LIMIT="${BUILDKITE_PLUGIN_JULIA_ARTIFACTS_SIZE_LIMIT:-10737418240}"
 
-if [[ "${BUILDKITE_PLUGIN_JULIA_ISOLATED_DEPOT:-true}" == "true" ]] && [[ -d "${ARTIFACTS_DIR}" ]]; then
-    ARTIFACTS_SIZE_HUMAN=$(du -h -s "${ARTIFACTS_DIR}" | cut -f 1)
-    # `-k` gives consistently the number of kilobytes on both macOS and Linux,
-    # without it BSD `du` would give the number of multiples of 512 bytes.
-    ARTIFACTS_SIZE=$(($(du -k -s "${ARTIFACTS_DIR}" | cut -f 1) * 1024))
-    echo "The artifact store size is: ${ARTIFACTS_SIZE_HUMAN}"
+if [[ "${BUILDKITE_PLUGIN_JULIA_ISOLATED_DEPOT:-true}" == "true" ]]; then
+    ARTIFACTS_DIR="${JULIA_DEPOT_PATH}/artifacts"
+    if [[ -d "${ARTIFACTS_DIR}" ]]; then
+        ARTIFACTS_SIZE_HUMAN=$(du -h -s "${ARTIFACTS_DIR}" | cut -f 1)
+        # `-k` gives consistently the number of kilobytes on macOS and Linux,
+        # without it BSD `du` would give the number of multiples of 512 bytes.
+        ARTIFACTS_SIZE=$(($(du -k -s "${ARTIFACTS_DIR}" | cut -f 1) * 1024))
+        echo "The artifact store size is: ${ARTIFACTS_SIZE_HUMAN}"
 
-    if [[ ${ARTIFACTS_SIZE} -gt ${ARTIFACTS_LIMIT} ]]; then
-        echo "This is greater than the limit (${ARTIFACTS_SIZE} > ${ARTIFACTS_LIMIT} bytes), so we will clear the artifact store"
+        if [[ ${ARTIFACTS_SIZE} -gt ${ARTIFACTS_LIMIT} ]]; then
+            echo "This is greater than the limit (${ARTIFACTS_SIZE} > ${ARTIFACTS_LIMIT} bytes), so we will clear the artifact store"
 
-        # Remove directories until we are below the limit
-        # We do this in Julia to avoid platform portability issues.
-        julia --color=yes -e '
-            function main(artifacts, size_str, limit_str)
-                size = parse(Int, size_str)
-                limit = parse(Int, limit_str)
+            # Remove directories until we are below the limit
+            # We do this in Julia to avoid platform portability issues.
+            julia --color=yes -e '
+                function main(artifacts, size_str, limit_str)
+                    size = parse(Int, size_str)
+                    limit = parse(Int, limit_str)
 
-                # Get all artifacts with their creation times
-                worklist = []
-                for dir in readdir(artifacts)
-                    path = joinpath(artifacts, dir)
-                    isdir(path) || continue
-                    push!(worklist, (; path, stat=stat(path)))
+                    # Get all artifacts with their creation times
+                    worklist = []
+                    for dir in readdir(artifacts)
+                        path = joinpath(artifacts, dir)
+                        isdir(path) || continue
+                        push!(worklist, (; path, stat=stat(path)))
+                    end
+
+                    # Sort by creation time (oldest first)
+                    sort!(worklist; by=entry->entry.stat.ctime)
+
+                    # Remove artifacts until we are under the limit
+                    for entry in worklist
+                        # artifacts can have funky permissions
+                        run(`chmod -R u+w $(entry.path)`)
+                        sz = parse(Int, split(read(`du -k -s $(entry.path)`, String))[1]) * 1024
+                        rm(entry.path; recursive=true)
+                        size -= sz
+                        size <= limit && break
+                    end
                 end
 
-                # Sort by creation time (oldest first)
-                sort!(worklist; by=entry->entry.stat.ctime)
-
-                # Remove artifacts until we are under the limit
-                for entry in worklist
-                    # artifacts can have funky permissions
-                    run(`chmod -R u+w $(entry.path)`)
-                    sz = parse(Int, split(read(`du -k -s $(entry.path)`, String))[1]) * 1024
-                    rm(entry.path; recursive=true)
-                    size -= sz
-                    size <= limit && break
-                end
-            end
-
-            main(ARGS...)
-        ' "${ARTIFACTS_DIR}" "${ARTIFACTS_SIZE}" "${ARTIFACTS_LIMIT}" || true
+                main(ARGS...)
+            ' "${ARTIFACTS_DIR}" "${ARTIFACTS_SIZE}" "${ARTIFACTS_LIMIT}" || true
+        fi
     fi
 fi
 
